package com.salesforce.marketingcloud.reporting;

import com.salesforce.marketingcloud.model.accessibility.AccessibilitySummary;
import com.salesforce.marketingcloud.model.accessibility.AxeNode;
import com.salesforce.marketingcloud.model.accessibility.AxeViolation;

/**
 * Builds an executive HTML report (summary) for accessibility scans.
 */
public final class AccessibilityHtmlReportBuilder {

    private AccessibilityHtmlReportBuilder() {}

    /**
     * Build a compact executive HTML summary for the provided AccessibilitySummary.
     * The HTML is intentionally lightweight and embeddable in Allure.
     */
    public static String buildExecutiveSummaryHtml(AccessibilitySummary summary) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!doctype html><html><head><meta charset=\"utf-8\">")
          .append("<title>Accessibility Executive Summary</title>")
          .append("<style>")
          .append("body{font-family:Arial,Helvetica,sans-serif;color:#222;margin:16px}")
          .append("h1{font-size:20px;margin-bottom:8px}")
          .append(".metrics{display:flex;gap:12px;margin-bottom:12px}")
          .append(".metric{padding:10px;border-radius:6px;background:#f5f5f7}")
          .append("table{border-collapse:collapse;width:100%;margin-top:12px}")
          .append("th,td{border:1px solid #e1e1e6;padding:8px;text-align:left}")
          .append("th{background:#f0f0f2}")
          .append(".severity-critical{background:#ffecec}")
          .append(".severity-serious{background:#fff4e6}")
          .append(".severity-moderate{background:#fffbe6}")
          .append(".severity-minor{background:#f7fff6}")
          .append("</style></head><body>");

        sb.append("<h1>Accessibility Executive Summary</h1>");

        sb.append("<div class=\"metrics\">");
        sb.append(metricHtml("Total Violations", String.valueOf(summary.getTotalViolations()), "#eef2ff"));
        sb.append(metricHtml("Critical", String.valueOf(summary.getCriticalCount()), "#ffecec"));
        sb.append(metricHtml("Serious", String.valueOf(summary.getSeriousCount()), "#fff4e6"));
        sb.append(metricHtml("Moderate", String.valueOf(summary.getModerateCount()), "#fffbe6"));
        sb.append(metricHtml("Minor", String.valueOf(summary.getMinorCount()), "#f7fff6"));
        sb.append("</div>");

        sb.append("<h2>Top Violations (by severity)</h2>");

        if (summary.getAxeResult() == null || summary.getAxeResult().getViolations() == null || summary.getAxeResult().getViolations().isEmpty()) {
            sb.append("<p>No violations found.</p>");
        } else {
            sb.append("<table><thead><tr><th>#</th><th>Rule ID</th><th>Impact</th><th>Description</th><th>Affected Target(s)</th><th>Failure Summary</th></tr></thead><tbody>");
            int i = 1;
            for (AxeViolation v : summary.getAxeResult().getViolations()) {
                // Limit rows to keep summary concise - show first 50
                if (i > 50) break;
                String targets = "";
                String failure = "";
                if (v.getNodes() != null && !v.getNodes().isEmpty()) {
                    StringBuilder t = new StringBuilder();
                    for (AxeNode n : v.getNodes()) {
                        if (n.getTarget() != null && !n.getTarget().isEmpty()) {
                            if (t.length() > 0) t.append("; ");
                            t.append(String.join(", ", n.getTarget()));
                        }
                    }
                    targets = t.toString();
                    failure = v.getNodes().get(0).getFailureSummary() == null ? "" : v.getNodes().get(0).getFailureSummary();
                }

                sb.append("<tr>");
                sb.append("<td>").append(i++).append("</td>");
                sb.append("<td>").append(escapeHtml(v.getId())).append("</td>");
                sb.append("<td>").append(escapeHtml(v.getImpact())).append("</td>");
                sb.append("<td>").append(escapeHtml(v.getDescription())).append("</td>");
                sb.append("<td>").append(escapeHtml(targets)).append("</td>");
                sb.append("<td>").append(escapeHtml(failure)).append("</td>");
                sb.append("</tr>");
            }
            sb.append("</tbody></table>");
        }

        sb.append("<footer style=\"margin-top:12px;font-size:11px;color:#666\">Report generated by AccessibilityHtmlReportBuilder</footer>");
        sb.append("</body></html>");
        return sb.toString();
    }

    private static String metricHtml(String title, String value, String bg) {
        return "<div class=\"metric\" style=\"background:" + bg + "\"><strong>" + escapeHtml(title) + "</strong><div style=\"font-size:18px;margin-top:6px\">" + escapeHtml(value) + "</div></div>";
    }

    private static String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");
    }
}
