package com.example.emailqa;

import com.example.emailqa.model.EmailAuditResult;
import com.example.emailqa.model.ValidationResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.stream.Collectors;

public class EmailAuditReportGenerator {
    private static final Logger logger = LoggerFactory.getLogger(EmailAuditReportGenerator.class);

    public String generateHtmlReport(EmailAuditResult result) {
        logger.info("Generating HTML audit report");
        StringBuilder sb = new StringBuilder();
        sb.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">\n");
        sb.append("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n");
        sb.append("<title>Email Audit Report</title>\n");
        sb.append("<style>body{font-family:Segoe UI,Roboto,Arial,sans-serif;margin:20px;color:#222}header{margin-bottom:20px}h1{font-size:20px;margin:0} .cards{display:flex;gap:12px;margin:12px 0} .card{padding:12px;border-radius:8px;background:#f7f9fb;border:1px solid #e3e8ee;min-width:140px} .card .num{font-weight:700;font-size:18px} table{border-collapse:collapse;width:100%;margin-top:12px} th,td{border:1px solid #e6ecf1;padding:10px;text-align:left;vertical-align:top} th{background:#f4f6f9} .badge{display:inline-block;padding:4px 8px;border-radius:12px;font-weight:600;color:#fff;font-size:12px} .pass{background:#28a745}.fail{background:#dc3545}.info{background:#6c757d}.major{background:#ffc107;color:#212529}.critical{background:#b02a37} .notes{white-space:pre-wrap;font-family:monospace;font-size:12px;color:#333} .issues{color:#b02a37;font-size:13px} footer{margin-top:20px;font-size:12px;color:#666}</style>\n");
        sb.append("</head><body>\n");

        sb.append("<header>");
        sb.append(String.format("<h1>Email Audit Report</h1>\n<p><strong>Subject:</strong> %s</p>\n<p><strong>Preheader:</strong> %s</p>", safe(result.getEmailSubject()), safe(result.getEmailPreheader())));
        sb.append("</header>");

        // Summary cards
        sb.append("<section class=\"cards\">\n");
        sb.append(cardHtml("Total Checks", String.valueOf(result.getValidations().size())));
        sb.append(cardHtml("Passed", String.valueOf(result.getPassedCount())));
        sb.append(cardHtml("Failed", String.valueOf(result.getFailedCount())));
        sb.append(cardHtml("Summary", safe(result.generateSummary())));
        sb.append("</section>\n");

        // Detailed table
        sb.append("<section><table>");
        sb.append("<thead><tr><th style=\"width:20%\">Validation</th><th style=\"width:10%\">Status</th><th style=\"width:10%\">Severity</th><th style=\"width:30%\">Notes</th><th style=\"width:30%\">Issues</th></tr></thead>");
        sb.append("<tbody>\n");
        for (ValidationResult v : result.getValidations()) {
            String statusClass = v.isPassed() ? "pass" : "fail";
            String statusText = v.isPassed() ? "PASS" : "FAIL";
            String severityClass = severityToClass(v.getSeverity());
            String issues = v.getIssues() == null ? "" : v.getIssues().stream().map(this::safe).collect(Collectors.joining("<br/>"));
            String notes = safe(v.getNotes());

            sb.append("<tr>");
            sb.append(String.format("<td>%s</td>", safe(v.getTestName())));
            sb.append(String.format("<td><span class=\"badge %s\">%s</span></td>", statusClass, statusText));
            sb.append(String.format("<td><span class=\"badge %s\">%s</span></td>", severityClass, safe(v.getSeverity())));
            sb.append(String.format("<td class=\"notes\">%s</td>", notes));
            sb.append(String.format("<td class=\"issues\">%s</td>", issues));
            sb.append("</tr>\n");
        }
        sb.append("</tbody></table></section>");

        sb.append("<footer>Generated by Email Audit Engine</footer>");
        sb.append("</body></html>");
        logger.info("HTML audit report generated");
        return sb.toString();
    }

    private String cardHtml(String title, String value) {
        return String.format("<div class=\"card\"><div style=\"font-size:12px;color:#666\">%s</div><div class=\"num\">%s</div></div>", safe(title), safe(value));
    }

    private String severityToClass(String sev) {
        if (sev == null) return "info";
        switch (sev.toUpperCase()) {
            case "CRITICAL": return "critical";
            case "MAJOR": return "major";
            case "INFO": return "info";
            default: return "info";
        }
    }

    private String safe(String s) {
        return s == null ? "" : escapeHtml(s);
    }

    private String escapeHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}